# A = anfitrion C = contendor
#version: "3.9"
#services:
#  miapp:
#    build: .
#    ports:
#      - "3000:3000"      
#    links:
#      - monguito
#  myback:
#    image: mongo
#    ports:
#      - "8080A:80C"
#    environment:
#      - name=value
#
#
#
# My version: docker-compose -v
# $ Docker Compose version v2.17.3
version: "3.9"
services:
    angular-service:
       container_name: ng-docker-example
       build: .
       ports:
           - "4200:80"
          #- "8080:80"